api:
  test-mode: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: # db url
    username: # db username
    password: # db password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  task:
    scheduling:
      pool:
        size: 2
line:
  bot:
    channel-secret: # line bot secret
    channel-token: # line bot token
    handler:
      path: /callback
taiwan:
  cwb:
    authorization: # cwb auth code
telegram:
  bot:
    token: # telegram token
    username: # telegram user name
web:
  url: # web url
