-- public.akb48_team_tp_image definition

-- Drop table

-- DROP TABLE public.akb48_team_tp_image;

CREATE TABLE public.akb48_team_tp_image (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	file_id varchar NOT NULL,
	file_name varchar NOT NULL,
	tag varchar NULL,
	CONSTRAINT akb48_team_tp_image_pk PRIMARY KEY (oid)
);


-- public.ig_image definition

-- Drop table

-- DROP TABLE public.ig_image;

CREATE TABLE public.ig_image (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	file_id varchar NOT NULL,
	file_name varchar NOT NULL,
	CONSTRAINT google_drive_image_pk PRIMARY KEY (oid)
);


-- public.imgur definition

-- Drop table

-- DROP TABLE public.imgur;

CREATE TABLE public.imgur (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	image_id varchar NULL,
	type_tag varchar NULL,
	person_tag varchar NULL,
	CONSTRAINT imgur_pk PRIMARY KEY (oid)
);


-- public.lang_live_streamer definition

-- Drop table

-- DROP TABLE public.lang_live_streamer;

CREATE TABLE public.lang_live_streamer (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	id varchar NOT NULL,
	status int4 NOT NULL,
	last_live_start_date_time timestamptz NULL,
	last_live_end_date_time timestamptz NULL,
	ig varchar NULL,
	ig_id varchar NULL,
	CONSTRAINT lang_live_anchor_pk PRIMARY KEY (oid)
);


-- public.line_bot_log definition

-- Drop table

-- DROP TABLE public.line_bot_log;

CREATE TABLE public.line_bot_log (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id varchar NOT NULL,
	message_text varchar NULL,
	create_date_time timestamptz NULL,
	"event" varchar NULL
);


-- public.service definition

-- Drop table

-- DROP TABLE public.service;

CREATE TABLE public.service (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	CONSTRAINT service_pk PRIMARY KEY (oid)
);


-- public.short_url definition

-- Drop table

-- DROP TABLE public.short_url;

CREATE TABLE public.short_url (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"key" varchar NOT NULL,
	url varchar NOT NULL,
	expired_date_time timestamptz NULL,
	click_count int4 NOT NULL DEFAULT 0,
	CONSTRAINT short_url_pk PRIMARY KEY (oid),
	CONSTRAINT short_url_un UNIQUE (key)
);


-- public."subscription" definition

-- Drop table

-- DROP TABLE public."subscription";

CREATE TABLE public."subscription" (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_oid int4 NOT NULL,
	service_oid int4 NOT NULL,
	"parameter" varchar NULL,
	CONSTRAINT subscription_pk PRIMARY KEY (oid)
);


-- public.telegram_user definition

-- Drop table

-- DROP TABLE public.telegram_user;

CREATE TABLE public.telegram_user (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	chat_id varchar NOT NULL,
	"name" varchar NULL,
	sub bool NULL,
	user_id varchar NULL,
	CONSTRAINT telegram_user_pk PRIMARY KEY (oid),
	CONSTRAINT telegram_user_un UNIQUE (chat_id)
);


-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	"oid" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id varchar NOT NULL,
	display_name varchar NOT NULL,
	picture_url varchar NULL,
	"role" varchar NULL,
	CONSTRAINT user_pk PRIMARY KEY (oid)
);
